
WITH cleaned_data AS (
  SELECT 
    TO_DATE(TIMESTAMP ,'MM/DD/YYYY HH24:MI') AS TIMESTAMP,
    SOIL_PH::FLOAT AS SOIL_PH,
    SOIL_MOISTURE::FLOAT AS SOIL_MOISTURE,
    SOIL_COMP::FLOAT AS SOIL_COMP,
    PHOSPHORUS_LEVEL::FLOAT AS PHOSPHORUS_LEVEL,
    ORGANIC_MATTER::FLOAT AS ORGANIC_MATTER,
    NITROGEN_LEVEL::FLOAT AS NITROGEN_LEVEL
  FROM {{ ref("stg_soil") }}
  WHERE SOIL_PH != 'NA'
    AND SOIL_MOISTURE != 'NA'
    AND SOIL_COMP != 'NA'
    AND PHOSPHORUS_LEVEL != 'NA'
    AND ORGANIC_MATTER != 'NA'
    AND NITROGEN_LEVEL != 'NA'
  LIMIT 100
)


SELECT * FROM cleaned_data 
ORDER BY TIMESTAMP DESC
LIMIT 100
