WITH cleaned_data AS (
  SELECT
    REPLACE(SENSOR_ID, '"', '') AS SENSOR_ID,
    TO_DATE(REPLACE(TIMESTAMP, '"', '')) AS TIMESTAMP,
    CAST(TEMPERATURE AS FLOAT) AS TEMPERATURE,
    CAST(HUMIDITY AS FLOAT) AS HUMIDITY,
    CAST(SOIL_MOISTURE AS FLOAT) AS SOIL_MOISTURE,
    CAST(LIGHT_INTENSITY AS FLOAT) AS LIGHT_INTENSITY
  FROM {{ ref("stg_sensor") }}
  WHERE
    TEMPERATURE != 'NA'
    AND HUMIDITY != 'NA'
    AND SOIL_MOISTURE != 'NA'
    AND LIGHT_INTENSITY != 'NA'

)

SELECT * FROM cleaned_data 
ORDER BY TIMESTAMP DESC