WITH cleaned_data AS (
  SELECT
    TO_DATE(TIMESTAMP, 'MM/DD/YYYY HH24:MI') AS TIMESTAMP,
    CASE
        WHEN REGEXP_LIKE(CROP_TYPE, '^[Corn]+$') THEN 'Corn'
        WHEN REGEXP_LIKE(CROP_TYPE, '^[Wheat]+$') THEN 'Wheat'
    ELSE
        CROP_TYPE    
    END CROP_TYPE,
    CAST(CROP_YIELD AS FLOAT) AS CROP_YIELD,
    GROWTH_STAGE,
    PEST_ISSUE
  FROM {{ ref("stg_crop") }}
  WHERE
    CROP_YIELD != 'NA'
    AND GROWTH_STAGE != 'NA'
    AND PEST_ISSUE != 'NA'
)


SELECT *
FROM cleaned_data
ORDER BY TIMESTAMP