WITH cleaned_data AS (
  SELECT
    SUBSTR(SENSOR_ID, 5, 4) AS SENSOR_ID,
    TO_DATE(TIMESTAMP, 'MM/DD/YYYY HH24:MI') AS TIMESTAMP,
    CASE
        WHEN IRRIGATION_METHOD LIKE 'Dr%' AND IRRIGATION_METHOD LIKE '%p' THEN 'Drip'
        WHEN IRRIGATION_METHOD LIKE 'Sp%' AND IRRIGATION_METHOD LIKE '%r' THEN 'Sprinkler'
    ELSE
        IRRIGATION_METHOD    
    END IRRIGATION_METHOD,
    WATER_SOURCE,
    CAST(IRRIGATION_DURATION_MIN AS FLOAT) AS IRRIGATION_DURATION_MIN
  FROM {{ ref("stg_irrigation") }}
  WHERE IRRIGATION_DURATION_MIN != 'NA'
)

SELECT * FROM cleaned_data 
ORDER BY TIMESTAMP DESC