WITH weather AS (
    SELECT W_C.TIMESTAMP AS TIMESTAMP,
        W_C.WEATHER_CONDITION AS WEATHER_CONDITION,
        W.AVG_WIND_SPEED AS AVG_WIND_SPEED,
        W.AVG_PRECIPITATION AS AVG_PRECIPITATION
    FROM ({{ most_frequent("WEATHER_CONDITION", "DFA23RAWDATA.DATAWIZ.dwh_weather",2) }}) AS W_C
    INNER JOIN (
            SELECT TIMESTAMP,
                   AVG(WIND_SPEED) AS AVG_WIND_SPEED, 
                   AVG(PRECIPITATION) AS AVG_PRECIPITATION
            FROM {{ ref("dwh_weather")}}
            GROUP BY TIMESTAMP
           ) AS W 
           ON W_C.TIMESTAMP = W.TIMESTAMP
),

soil AS (
    SELECT TIMESTAMP,
        AVG(SOIL_COMP) AS AVG_SOIL_COMP, 
        AVG(SOIL_MOISTURE) AS AVG_SOIL_MOISTURE,
        AVG(SOIL_PH) AS AVG_SOIL_PH,
        AVG(PHOSPHORUS_LEVEL) AS AVG_PHOSPHORUS_LEVEL,
        AVG(NITROGEN_LEVEL) AS AVG_NITROGEN_LEVEL,
        AVG(ORGANIC_MATTER) AS AVG_ORGANIC_MATTER
    FROM {{ ref("dwh_soil")}}
    GROUP BY TIMESTAMP
),

sensor AS (
    SELECT TIMESTAMP,
        AVG(TEMPERATURE) AS AVG_TEMPERATURE, 
        AVG(HUMIDITY) AS AVG_HUMIDITY,
        AVG(LIGHT_INTENSITY) AS AVG_LIGHT_INTENSITY
    FROM {{ ref("dwh_sensor")}}
    GROUP BY TIMESTAMP
),

crop AS (
    SELECT TIMESTAMP,
        COUNT(DISTINCT(CROP_TYPE)) AS NUM_DISTINCT_AFFECTED_CROPS, 
        COUNT(DISTINCT(PEST_ISSUE)) AS NUM_DISTINCT_PESTS_RECORDED,
        COUNT(*) AS  NUM__PESTS_ISSUES_RECORDED
    FROM {{ ref("dwh_crop")}}
    WHERE PEST_ISSUE != 'No Pest Issue'
    GROUP BY TIMESTAMP
),

irrigation AS (
    SELECT I_M.TIMESTAMP AS TIMESTAMP,
        I_M.IRRIGATION_METHOD AS IRRIGATION_METHOD,
        W_S.WATER_SOURCE AS WATER_SOURCE,
        I_D_M.IRRIGATION_DURATION_MIN AS IRRIGATION_DURATION_MIN
    FROM ({{ most_frequent("IRRIGATION_METHOD", "DFA23RAWDATA.DATAWIZ.dwh_irrigation",1) }}) AS I_M
    INNER JOIN ({{ most_frequent("WATER_SOURCE", "DFA23RAWDATA.DATAWIZ.dwh_irrigation",1) }}) AS W_S  
                ON I_M.TIMESTAMP = W_S.TIMESTAMP
    INNER JOIN (
                SELECT TIMESTAMP,
                    SUM(IRRIGATION_DURATION_MIN) AS IRRIGATION_DURATION_MIN
                FROM {{ ref("dwh_irrigation")}}
                GROUP BY TIMESTAMP
            ) AS I_D_M 
            ON I_M.TIMESTAMP = I_D_M.TIMESTAMP
)

-- Join all the subqueries on TIMESTAMP
SELECT w.TIMESTAMP,
    w.AVG_WIND_SPEED,
    w.AVG_PRECIPITATION,
    w.WEATHER_CONDITION,
    s.AVG_SOIL_COMP,
    s.AVG_SOIL_MOISTURE,
    s.AVG_SOIL_PH,
    s.AVG_PHOSPHORUS_LEVEL,
    s.AVG_NITROGEN_LEVEL,
    s.AVG_ORGANIC_MATTER,
    se.AVG_TEMPERATURE,
    se.AVG_HUMIDITY,
    se.AVG_LIGHT_INTENSITY,
    c.NUM_DISTINCT_AFFECTED_CROPS,
    c.NUM_DISTINCT_PESTS_RECORDED,
    c.NUM__PESTS_ISSUES_RECORDED,
    i.IRRIGATION_METHOD,
    i.WATER_SOURCE,
    i.IRRIGATION_DURATION_MIN
FROM weather w
INNER JOIN soil s ON w.TIMESTAMP = s.TIMESTAMP
INNER JOIN sensor se ON w.TIMESTAMP = se.TIMESTAMP
INNER JOIN crop c ON w.TIMESTAMP = c.TIMESTAMP
INNER JOIN irrigation i ON w.TIMESTAMP = i.TIMESTAMP
