WITH weather AS (
    SELECT TIMESTAMP,
        AVG(WIND_SPEED) AS AVG_WIND_SPEED, 
        AVG(PRECIPITATION) AS AVG_PRECIPITATION,
        MAX(WEATHER_CONDITION) AS WEATHER_CONDITION
    FROM {{ ref("dwh_weather")}}
    GROUP BY TIMESTAMP
),

soil AS (
    SELECT TIMESTAMP,
        AVG(SOIL_COMP) AS AVG_SOIL_COMP, 
        AVG(SOIL_MOISTURE) AS AVG_SOIL_MOISTURE,
        AVG(SOIL_PH) AS AVG_SOIL_PH,
        AVG(PHOSPHORUS_LEVEL) AS AVG_PHOSPHORUS_LEVEL,
        AVG(NITROGEN_LEVEL) AS AVG_NITROGEN_LEVEL,
        AVG(ORGANIC_MATTER) AS AVG_ORGANIC_MATTER
    FROM {{ ref("dwh_soil")}}
    GROUP BY TIMESTAMP
),

sensor AS (
    SELECT TIMESTAMP,
        AVG(TEMPERATURE) AS AVG_TEMPERATURE, 
        AVG(HUMIDITY) AS AVG_HUMIDITY,
        AVG(LIGHT_INTENSITY) AS AVG_LIGHT_INTENSITY
    FROM {{ ref("dwh_sensor")}}
    GROUP BY TIMESTAMP
),

crop AS (
    SELECT TIMESTAMP,
        COUNT(DISTINCT(CROP_TYPE)) AS NUM_DISTINCT_AFFECTED_CROPS, 
        COUNT(*) AS NUM_DISTINCT_PESTS_RECORDED 
    FROM {{ ref("dwh_crop")}}
    GROUP BY TIMESTAMP
),

irrigation AS (
    SELECT TIMESTAMP,
        MAX(IRRIGATION_METHOD) AS IRRIGATION_METHOD,
        MAX(WATER_SOURCE) AS WATER_SOURCE,
        SUM(IRRIGATION_DURATION_MIN) AS IRRIGATION_DURATION_MIN
    FROM {{ ref("dwh_irrigation")}}
    GROUP BY TIMESTAMP
)

-- Join all the subqueries on TIMESTAMP
SELECT w.TIMESTAMP,
    w.AVG_WIND_SPEED,
    w.AVG_PRECIPITATION,
    w.WEATHER_CONDITION,
    s.AVG_SOIL_COMP,
    s.AVG_SOIL_MOISTURE,
    s.AVG_SOIL_PH,
    s.AVG_PHOSPHORUS_LEVEL,
    s.AVG_NITROGEN_LEVEL,
    s.AVG_ORGANIC_MATTER,
    se.AVG_TEMPERATURE,
    se.AVG_HUMIDITY,
    se.AVG_LIGHT_INTENSITY,
    c.NUM_DISTINCT_AFFECTED_CROPS,
    c.NUM_DISTINCT_PESTS_RECORDED,
    i.IRRIGATION_METHOD,
    i.WATER_SOURCE,
    i.IRRIGATION_DURATION_MIN
FROM weather w
INNER JOIN soil s ON w.TIMESTAMP = s.TIMESTAMP
INNER JOIN sensor se ON w.TIMESTAMP = se.TIMESTAMP
INNER JOIN crop c ON w.TIMESTAMP = c.TIMESTAMP
INNER JOIN irrigation i ON w.TIMESTAMP = i.TIMESTAMP
